name: Glocalsclub
favicon: null
layout_spectrum: 0.07607870432548225
typography_spectrum: 0.4761117557063699
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1893166594672948
  lightness: 0.49478934425860643
  saturation: 0.9624221920967102
  rhythmicContrast: 0.5254954870324582
purpose: []
